### PYTHON PANDAS PART 1

 IN PART WE ARE DOING LEARN ABOUT

1. Pandas Dataframe
2. Pandas Series
3. Pandas Basic Operations

In [ ]:
! pip install pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [4]:
# create Dataframe
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["Row1",
                                                          "Row2","Row3",
                                                          "Row4","Row5"],columns=["column1",
                                                                                 "column2",
                                                                                 "column3",
                                                                                 "column4"])


In [5]:
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [6]:
df.tail()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [9]:
df.describe()

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [10]:
# indexing
## Columnname, rowindex[loc],rowindex columnindex number[.iloc]
df.head()

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
Row3        8        9       10       11
Row4       12       13       14       15
Row5       16       17       18       19

In [15]:
df.iloc[2:4,1:3]

column2  column3
Row3        9       10
Row4       13       14

In [16]:
df.iloc[:3,:3]

column1  column2  column3
Row1        0        1        2
Row2        4        5        6
Row3        8        9       10

In [28]:
# convert dataframe into arrays
df.iloc[:,1:3].values

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [31]:
# basic operations
df.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [32]:
df=pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["Row1",
                                                      "Row2"],columns=["Column1",
                                                                             "Column2",
                                                                             "Column3",
                                                                             ])
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [33]:
df.isnull().sum()

Column1    0
Column2    1
Column3    0
dtype: int64

In [34]:
df.isnull().sum()==0

Column1     True
Column2    False
Column3     True
dtype: bool

In [35]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [36]:
df['Column3'].value_counts()

4    1
2    1
Name: Column3, dtype: int64

In [37]:
df

Column1  Column2  Column3
Row1        1      NaN        2
Row2        1      3.0        4

In [40]:
df['Column3'].unique()

array([2, 4], dtype=int64)

In [41]:
df[df['Column2']>2]

Column1  Column2  Column3
Row2        1      3.0        4